## geotop_SoilPropertyCalibration_EvaluateLHSsaturation.R
#' This script is intended to determine whether or not the results from an automated calibration
#' are "saturated", AKA adding additional samples is not likely to improve performance.

rm(list=ls())

# git directory for relative paths
git.dir <- "C:/Users/Sam/WorkGits/SoilPropertyCalibrationBasic/ARF1D/"

# which geotop version
geo.dir <- "geotop_NRCS/"
#geo.dir <- "geotop/"

require(lubridate)
require(ggplot2)
require(reshape2)
require(dplyr)
require(gridExtra)

## read in output data
# this is generated by the script: geotop_SoilPropertyCalibration_SelectBest+Plot_NRCS.R
df.out <- read.csv(paste0(git.dir, geo.dir, "SoilPropertyCalibration/SoilPropertyCalibration_FitMetrics_Summary.csv"), stringsAsFactors=F)

## we are going to evaluate the performance of the calibration period for both VWC and temperature based on RMSE
df.cal.temp <- subset(df.out, period=="cal" & variable=="temp")
df.cal.VWC  <- subset(df.out, period=="cal" & variable=="VWC")

# put into rank order
df.cal.temp <- df.cal.temp[order(df.cal.temp$RMSE.mean),]
df.cal.VWC  <- df.cal.VWC[order(df.cal.VWC$RMSE.mean),]

# add rank column
df.cal.temp$rank <- seq(1, dim(df.cal.temp)[1])
df.cal.VWC$rank  <- seq(1, dim(df.cal.VWC)[1])

# combine into single data frame
df.cal <- rbind(df.cal.temp, df.cal.VWC)

# make plot
p.cal <- 
  ggplot(df.cal, aes(x=rank, y=RMSE.mean)) +
  geom_line() +
  facet_wrap(~variable, ncol=1, scales="free_y") +
  scale_x_reverse(expand=c(0,0)) + 
  theme_bw() +
  theme(panel.grid=element_blank())

# (i think) if the LHS sample is saturated, the line should approach a horizontal asymptote,
# as all the top-ranked samples would perform approximately the same